### ISSUE TITLE
[REQUEST] Source code release for recent 4.19 devices

### ISSUE THREAD

**Issue by erfanoabdi** [MotorolaMobilityLLC/vendor-cirrus-audio-dlkm#1]
Please release source code of this modules for device smith, tag: MMI-QPS30.205-Q3-43-16-3

as i can see many other moto devices have cirrus modules such as racer
but new tag release is not happening here, please consider updating this repo on relevant kernel releases

Thanks 
cc @awheeler-mmi @charleseb @chenyt9

**Comment by charleseb** [comment]
Hi @erfanoabdi,

I'm working to release this version. I missed this git, sorry about that. It will be released asap.

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/vendor-cirrus-audio-dlkm/releases/tag/MMI-QPS30.205-Q3-43-16-3

**Comment by erfanoabdi** [comment]
Thanks alot
